{
 "title": "JTI - CPU / Memory",
 "tags": [
  "juniper",
  "opennti",
  "jti",
  "streaming"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host_regex",
    "label": "Device",
    "query": "SHOW TAG VALUES FROM \"juniperNetworks.cpu_memory_util_ext\" WITH KEY = \"device\""
   },
   {
    "name": "app_name",
    "label": "Application",
    "query": "SHOW TAG VALUES FROM \"juniperNetworks.cpu_memory_util_ext\" WITH KEY = \"utilization.application_utilization.name\" WHERE \"device\" =~ /$host_regex/"
   },
   {
    "name": "u_name",
    "query": "SHOW TAG VALUES FROM \"juniperNetworks.cpu_memory_util_ext\" WITH KEY = \"utilization.name\" WHERE \"device\" =~ /$host_regex/"
   },
   { "name": "group_by", "query": "1s,5s,10s,30s,1m,5m" }
  ]
 },
 "panels": [
  { "title": "CPU / Mem Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU / Memory - Bytes allocated per application",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]-[[tag_utilization.application_utilization.name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  \"utilization.application_utilization.bytes_allocated\" FROM \"juniperNetworks.cpu_memory_util_ext\" WHERE \"device\" =~ /^$host_regex/ AND \"utilization.application_utilization.name\" =~ /^$app_name$/ AND $timeFilter GROUP BY  \"device\", \"utilization.application_utilization.name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU / Memory - frees per application",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]-[[tag_utilization.application_utilization.name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"utilization.application_utilization.frees\" FROM \"juniperNetworks.cpu_memory_util_ext\" WHERE \"device\" =~ /^$host_regex/ AND \"utilization.application_utilization.name\" =~ /^$app_name$/ AND $timeFilter GROUP BY  \"device\", \"utilization.application_utilization.name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU / Memory - Bytes allocated per application(delta)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]--[[tag_utilization.application_utilization.name]]",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      {
       "params": [
        "utilization.application_utilization.name"
       ],
       "type": "tag"
      },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "juniperNetworks.cpu_memory_util_ext",
     "query": "SELECT non_negative_derivative(mean(\"utilization.application_utilization.bytes_allocated\"), 1s)*8 FROM \"juniperNetworks.cpu_memory_util_ext\" WHERE \"device\" =~ /^$host_regex/ AND \"utilization.application_utilization.name\" =~ /^$app_name$/ AND $timeFilter GROUP BY time($__interval), \"device\", \"utilization.application_utilization.name\" fill(null)",
     "select": [
      [
       {
        "params": [
         "utilization.application_utilization.allocations"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$host_regex/" },
      {
       "condition": "AND",
       "key": "utilization.application_utilization.name",
       "operator": "=~",
       "value": "/^$app_name$/"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU / Memory - frees per application (delta)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]--[[tag_utilization.application_utilization.name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "juniperNetworks.cpu_memory_util_ext",
     "query": "SELECT non_negative_derivative(mean(\"utilization.application_utilization.frees\"), 1s) FROM \"juniperNetworks.cpu_memory_util_ext\" WHERE \"device\" =~ /^$host_regex/ AND \"utilization.application_utilization.name\" =~ /^$app_name$/ AND $timeFilter GROUP BY time($__interval), \"device\", \"utilization.application_utilization.name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU / Memory Bytes allocated Global - Kernel",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]-[[tag_utilization.name]]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"utilization.bytes_allocated\" FROM \"juniperNetworks.cpu_memory_util_ext\" WHERE \"device\" =~ /^$host_regex/ AND \"utilization.name\" =~ /^$u_name$/ AND $timeFilter GROUP BY  \"device\", \"utilization.name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU / Memory Allocations per application (delta)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]][[tag_utilization.application_utilization.name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"utilization.application_utilization.allocations\"), 1s) FROM \"juniperNetworks.cpu_memory_util_ext\" WHERE \"device\" =~ /^$host_regex/ AND \"utilization.application_utilization.name\" =~ /^$app_name$/ AND $timeFilter GROUP BY time($__interval), \"device\", \"utilization.application_utilization.name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU / Memory Bytes allocated Global - Kernel  (delta)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]-[[tag_utilization.name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"utilization.bytes_allocated\"), 1s)*8 FROM \"juniperNetworks.cpu_memory_util_ext\" WHERE \"device\" =~ /^$host_regex/ AND \"utilization.name\" =~ /^$u_name$/ AND $timeFilter GROUP BY time($__interval), \"device\", \"utilization.name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU / Memory Allocations per application",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]-[[tag_utilization.application_utilization.name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"utilization.application_utilization.allocations\" FROM \"juniperNetworks.cpu_memory_util_ext\" WHERE \"device\" =~ /^$host_regex/ AND \"utilization.application_utilization.name\" =~ /^$app_name$/ AND $timeFilter GROUP BY \"device\", \"utilization.application_utilization.name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}